name = "libhello"
description = "Basic library demonstration project"
version = "0.1.25943+selftest_by_alr_publish_action"
tags = ["hello", "demo", "library"]
licenses = "MIT"
website = "https://github.com/alire-project/libhello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[origin]
commit = "8f302e12225a014b344876381daeec16a18ff9c4"
url = "git+file:/home/runner/work/alr-publish/alr-publish/libhello.upstream"

