name = "libhello"
description = "Basic library demonstration project"
version = "0.1.27399+selftest_by_alr_publish_action"
tags = ["hello", "demo", "library"]
licenses = "MIT"
website = "https://github.com/alire-project/libhello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[origin]
commit = "ad53f2b17f57cbc615ff001b3f4375ad3681c586"
url = "git+file:/home/runner/work/alr-publish/alr-publish/libhello.upstream"

