name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-34612694+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "93719ac35be05d5f5c5e037f4eb6a72ba62e4bc1"
url = "git+file:/tmp/tmp_89ws7be/publish__submit-request-cancel/hello_upstream"

