name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-11793704+autotest_by_mosteo@kukumo"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "7efa47c47076f0590a2b8ddc6b03fd36226ba20a"
url = "git+file:/tmp/tmp4y_30u97/publish__submit-request-cancel/hello_upstream"

