name = "hello"
description = "'Hello, world!' demonstration project"
version = "0.1.0-7854619+autotest_by_mosteo@zelda"
tags = ["hello", "demo"]
licenses = "MIT"
website = "https://github.com/alire-project/hello"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

executables = ["hello"]

[[depends-on]]
libhello = "^1.0"

[origin]
commit = "f50ec9a1070a725a2f291c0deb48f26190935409"
url = "git+file:/tmp/tmpjhfdzj1n/publish__submit-request-cancel/hello_upstream"

